openapi: 3.0.1
info:
  title: Documentación de la API de la Plantilla
  description: 'Aquí se encuentra la información correspondiente a los endpoints de 
    interacción con la API para facilitar el consumo de esta. (Esto es una plantilla para 
    representar el correcto funcionamiento del Swagger y actualmente no contiene ningun
    endpoint de la API, deberán agregarse cuando ya se encuentren disponibles).'
paths:
  $include: "paths/paths.yaml"
components:
  schemas:
    $include: "schemas/schemas.yaml"
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []